services:
  core:
    build:
      context: ./core
      target: app_dev
    volumes:
      - ./core:/srv/www
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_API_MODEL=${OPENAI_API_MODEL}

  web:
    build:
      context: ./web
      target: app_dev
    volumes:
      - ./web:/srv/www
    environment:
      - CORE_API_BASE_URL=${CORE_API_BASE_URL}
    
  proxy:
    build:
      context: ./proxy
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./proxy/Caddyfile:/etc/caddy/Caddyfile
      - ./proxy/site:/srv
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - DOMAIN=${DOMAIN}

volumes:
  caddy_data:
  caddy_config:
