import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { useState } from 'react';

interface DbmlAssistantProps {
  // eslint-disable-next-line no-unused-vars
  setDbmlCode: (dbmlCode: string) => void;
}

const DbmlAssistant = ({ setDbmlCode }: DbmlAssistantProps) => {
  const [isGenerating, setIsGenerating] = useState(false);
  const [aiPrompt, setAiPrompt] = useState('');
  // Handle AI generation (placeholder for now)
  const handleAiGenerate = () => {
    setIsGenerating(true);
    // Simulate API call
    setTimeout(() => {
      setIsGenerating(false);
      // For now, just append the prompt as a comment to the DBML
      setDbmlCode(`// some dbml code generated by ai`);
      setAiPrompt('');
    }, 1500);
  };

  return (
    <>
      <div className="flex-1 p-2 overflow-y-auto">
        <div className="bg-slate-100 dark:bg-slate-800 p-2 rounded-lg mb-2 max-w-[80%]">
          <p className="text-sm">How can I help you with your database schema?</p>
        </div>
      </div>
      <div className="p-2 border-t border-slate-200 dark:border-slate-800">
        <div className="flex gap-2">
          <Textarea
            placeholder="Describe your database schema..."
            value={aiPrompt}
            onChange={(e) => setAiPrompt(e.target.value)}
            className="min-h-[60px] resize-none text-sm"
          />
          <Button
            onClick={handleAiGenerate}
            disabled={isGenerating || !aiPrompt.trim()}
            className="bg-gradient-to-r from-blue-500 to-purple-600 hover:from-blue-600 hover:to-purple-700 text-white self-end">
            {isGenerating ? (
              <div className="flex items-center">
                <div className="animate-spin mr-2 h-4 w-4 border-2 border-white border-t-transparent rounded-full"></div>
                <span>Generating...</span>
              </div>
            ) : (
              <span>Send</span>
            )}
          </Button>
        </div>
      </div>
    </>
  );
};

export default DbmlAssistant;
