services:
  user-service:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - "8080:8080"
    networks:
      - user-service-network
    env_file:
      - .env
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/scafoldr_app_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
      - SPRING_DEVTOOLS_LIVERELOAD_ENABLED=true
      - SPRING_DOCKER_COMPOSE_ENABLED=false
      - SPRING_PROFILES_ACTIVE=dev
      - MAVEN_OPTS=-Dmaven.repo.local=/root/.m2/repository
    volumes:
      - ./src:/app/src
      - ~/.m2:/root/.m2
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    command: [ "/docker-entrypoint.sh" ]

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=scafoldr_app_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - user-service-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d scafoldr_app_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

networks:
  user-service-network:

volumes:
  postgres_data:


