# Use the official Redis image as the base image
FROM redis:latest

# Expose the default Redis port
EXPOSE 6379

# The default command to run Redis server is already defined in the base image,
# but can be overridden if needed.
CMD ["redis-server"]
